<?php
namespace App\Database;

/**
 * PostgreSQL. translate() überträgt das bisherige SQLite-SQL der App:
 *  - camelCase-Bezeichner werden gequotet ("kundeId"), sonst faltet PostgreSQL sie auf Kleinbuchstaben
 *  - INSERT OR IGNORE → ON CONFLICT DO NOTHING, PRAGMA table_info → information_schema
 *  - DDL: AUTOINCREMENT/INTEGER/REAL/COLLATE NOCASE/datetime('now') → PostgreSQL-Typen
 */
final class PgsqlDialect extends Dialect
{
    /** @var array<string,string> */
    private static array $cache = [];

    public function translate(string $sql): string
    {
        if (isset(self::$cache[$sql])) return self::$cache[$sql];
        $original = $sql;

        if (preg_match('/^\s*PRAGMA\s+table_info\s*\(\s*"?([A-Za-z0-9_]+)"?\s*\)\s*;?\s*$/i', $sql, $m)) {
            $out = "SELECT column_name AS name, data_type AS type FROM information_schema.columns"
                 . " WHERE table_schema = current_schema() AND table_name = '" . $m[1] . "' ORDER BY ordinal_position";
        } else {
            $isDdl = (bool)preg_match('/^(?:\s+|--[^\n]*\n)*(CREATE\s+TABLE|ALTER\s+TABLE|CREATE\s+(UNIQUE\s+)?INDEX)/i', $sql);
            if ($isDdl) {
                $sql = (string)preg_replace("/datetime\\(\\s*'now'\\s*\\)/i", "to_char(now(), 'YYYY-MM-DD HH24:MI:SS')", $sql);
            }
            $out = '';
            foreach (self::segments($sql) as [$isCode, $part]) {
                if ($isCode) {
                    if ($isDdl) $part = self::translateDdl($part);
                    // SQLite-LIKE ignoriert Groß-/Kleinschreibung (ASCII), PostgreSQL-LIKE nicht.
                    else $part = (string)preg_replace('/\bLIKE\b/i', 'ILIKE', $part);
                    $part = self::quoteMixedCase($part);
                }
                $out .= $part;
            }
            if (preg_match('/^\s*INSERT\s+OR\s+IGNORE\s+INTO\b/i', $out)) {
                $out = preg_replace('/^\s*INSERT\s+OR\s+IGNORE\s+INTO\b/i', 'INSERT INTO', $out);
                $out = rtrim($out, " \t\r\n;") . ' ON CONFLICT DO NOTHING';
            }
        }
        if (count(self::$cache) > 2000) self::$cache = [];
        return self::$cache[$original] = $out;
    }

    /**
     * Zerlegt SQL in Code und Literale/gequotete Bezeichner, damit nur Code umgeschrieben wird.
     * @return list<array{0:bool,1:string}>
     */
    private static function segments(string $sql): array
    {
        $parts = [];
        $len = strlen($sql);
        $buf = '';
        for ($i = 0; $i < $len; $i++) {
            $c = $sql[$i];
            if ($c === '-' && ($sql[$i + 1] ?? '') === '-') {
                if ($buf !== '') { $parts[] = [true, $buf]; $buf = ''; }
                $j = strpos($sql, "\n", $i);
                $j = $j === false ? $len - 1 : $j;
                $parts[] = [false, substr($sql, $i, $j - $i + 1)];
                $i = $j;
                continue;
            }
            if ($c === "'" || $c === '"') {
                if ($buf !== '') { $parts[] = [true, $buf]; $buf = ''; }
                $j = $i + 1;
                while ($j < $len) {
                    if ($sql[$j] === $c) {
                        if ($j + 1 < $len && $sql[$j + 1] === $c) { $j += 2; continue; }
                        break;
                    }
                    $j++;
                }
                $parts[] = [false, substr($sql, $i, $j - $i + 1)];
                $i = $j;
                continue;
            }
            $buf .= $c;
        }
        if ($buf !== '') $parts[] = [true, $buf];
        return $parts;
    }

    private static function quoteMixedCase(string $code): string
    {
        return (string)preg_replace_callback(
            '/(?<![:\w$])([A-Za-z_][A-Za-z0-9_]*)/',
            static function (array $m): string {
                $w = $m[1];
                return (preg_match('/[a-z]/', $w) && preg_match('/[A-Z]/', $w)) ? '"' . $w . '"' : $w;
            },
            $code,
        );
    }

    private static function translateDdl(string $code): string
    {
        $rules = [
            '/\bINTEGER\s+PRIMARY\s+KEY(\s+AUTOINCREMENT)?/i' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            '/\bINTEGER\b/i'                                  => 'BIGINT',
            '/\bREAL\b/i'                                     => 'DOUBLE PRECISION',
            '/\bTEXT\b([^,()]*?)\s+COLLATE\s+NOCASE/i'        => 'CITEXT$1',
            '/\s+COLLATE\s+NOCASE/i'                          => '',
            '/(REFERENCES\s+\w+\s*\([^)]*\)(?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|SET\s+NULL|SET\s+DEFAULT|RESTRICT|NO\s+ACTION))*)/i'
                => '$1 DEFERRABLE INITIALLY IMMEDIATE',
        ];
        return (string)preg_replace(array_keys($rules), array_values($rules), $code);
    }

    public function tableNames(\PDO $pdo): array
    {
        return $pdo->query("SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type = 'BASE TABLE' ORDER BY table_name")
            ->fetchAll(\PDO::FETCH_COLUMN);
    }

    public function columnTypes(\PDO $pdo, string $table): array
    {
        $stmt = $pdo->prepare('SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? ORDER BY ordinal_position');
        $stmt->execute([$table]);
        $types = [];
        foreach ($stmt->fetchAll(\PDO::FETCH_ASSOC) as $col) {
            $t = (string)$col['data_type'];
            $types[$col['column_name']] = in_array($t, ['bigint', 'integer', 'smallint'], true) ? 'int'
                : (in_array($t, ['double precision', 'real', 'numeric'], true) ? 'float' : 'text');
        }
        return $types;
    }

    /** @return list<string> */
    public function notNullColumns(\PDO $pdo, string $table): array
    {
        $stmt = $pdo->prepare("SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? AND is_nullable = 'NO'");
        $stmt->execute([$table]);
        return $stmt->fetchAll(\PDO::FETCH_COLUMN);
    }

    public function groupConcat(string $expr, string $separator): string
    {
        return "string_agg(CAST({$expr} AS TEXT), {$separator})";
    }

    public function beginExclusive(\PDO $pdo, string $lockName): void
    {
        $pdo->beginTransaction();
        $pdo->prepare('SELECT pg_advisory_xact_lock(hashtext(?))')->execute([$lockName]);
    }

    public function beginSnapshot(\PDO $pdo): void
    {
        $pdo->beginTransaction();
        $pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY');
    }

    public function relaxForeignKeys(\PDO $pdo): void
    {
        $pdo->exec('SET CONSTRAINTS ALL DEFERRED');
    }

    public function foreignKeyViolations(\PDO $pdo): int
    {
        // Verzögerte Fremdschlüssel prüft PostgreSQL beim Commit; Fehler dort bricht den Import ab.
        return 0;
    }

    public function resetSequences(\PDO $pdo, array $tables): void
    {
        $stmt = $pdo->prepare(
            "SELECT column_name FROM information_schema.columns
              WHERE table_schema = current_schema() AND table_name = ? AND is_identity = 'YES'"
        );
        foreach ($tables as $table) {
            $stmt->execute([$table]);
            foreach ($stmt->fetchAll(\PDO::FETCH_COLUMN) as $col) {
                $qt = self::quoteIdentifier($table);
                $qc = self::quoteIdentifier($col);
                $pdo->query("SELECT setval(pg_get_serial_sequence('{$qt}', '{$col}'), GREATEST(COALESCE((SELECT MAX({$qc}) FROM {$qt}), 0), 1), (SELECT COUNT(*) > 0 FROM {$qt}))");
            }
        }
    }

    public function prepareSchema(\PDO $pdo): void
    {
        // citext bildet SQLites COLLATE NOCASE nach (z. B. Benutzername ohne Groß-/Kleinschreibung).
        $pdo->exec('CREATE EXTENSION IF NOT EXISTS citext');
    }
}
